### ISSUE TITLE
[feature] environment and env variables

### ISSUE THREAD

**Issue by florentvaldelievre** [markround/tiller#11]
Would it be possible to use environment variables coming from differences sources ( env, tiller_json) directly in yaml file ?

environments/{env}.yaml
common:
  exec: cat $FILENAME

server.xml.erb:
  target: /var/lib/tomcat7/conf/server.xml

**Comment by markround** [comment]
Sorry, I don't think this is possible as you'd need to parse and do variable interpolation on the YAML file first. You might be able to workaround this by generating a "exec" script via a template first (for your example). If this doesn't work for you and you really need this as a feature, please let me know and I'll have another think...
