### ISSUE TITLE
Can't merge defaults in defaults.d v0.62

### ISSUE THREAD

**Issue by weiyinteo** [markround/tiller#12]
Hi,

It seems a bug was introduced and I cannot merge defaults defined in defaults.d directly. 

It seems to be related to line 30 of lib/tiller/data/defaults.rb
          @defaults_hash.deep_merge!() if yaml != false
which should be
           @defaults_hash.deep_merge!(**yaml**) if yaml != false

Best regards,
Wei

**Comment by markround** [comment]
Good catch! Fixed in commit 3c8b8288c836de023a9f7aab249c4ac30e08fc1f, I will build and push a new gem now.

**Comment by markround** [comment]
Gem pushed, you should now be able to grab 0.6.3 which resolves this. Thanks again for your bug report and fix!
