### ISSUE TITLE
issue with tiller installation in Docker

### ISSUE THREAD

**Issue by sanjeevtripurari** [markround/tiller#13]
Any clue how to fix it, though it says >=1.9.2 for ruby, where as ruby 1.9.3 is installed

Setting up ruby1.9.3 (1.9.3.0-1ubuntu2.10) ...

Step 3 : RUN gem install tiller
 ---> Running in b7bcc9f35c84
ERROR:  Error installing tiller:
	tiller requires Ruby version >= 1.9.2.

**Comment by markround** [comment]
Can you share your Dockerfile so I can try and recreate the issue?

Thanks,

-Mark

**Comment by sanjeevtripurari** [comment]
Mark, got the issue, this image is having problem

FROM ubuntu:precise-20150212

tested with ubuntu:latest it works fine

Thanks

**Comment by sanjeevtripurari** [comment]
Just an update, we can fix in ubuntu:precise-20150212
by update-alertnatives

<code>
RUN apt-get update && apt-get install -y ruby1.9.3
RUN update-alternatives --install /usr/bin/ruby ruby  /usr/bin/ruby1.9.3 400
RUN update-alternatives --install /usr/bin/gem gem /usr/bin/gem1.9.1 400

RUN gem install tiller
</code>

**Comment by markround** [comment]
Thanks for the update!
