### ISSUE TITLE
"Update on value change"

### ISSUE THREAD

**Issue by EugenMayer** [markround/tiller#22]
Similar to confd or consul-template, is there any way / idea to trigger tiller if values change in "consul" or lets say the datasource?

I am not sure if this is at all implementable, since as far as i understand, tiller has no "daemon" mode, right? So its a one-shot only. I guess one could use a "wrapper" script to listen for the data-source events and then trigger tiller, but this would make quiet an effort per server, so i ask myself, if we could do this in tiler, or lets say a tillerd companion.

This is e.g. the feature which blocks me from using tiller compared to consul-template.

Any ideas?

**Comment by markround** [comment]
Hi,

The quick answer to this is "No", with a "However..." added. 

Tiller as it stands doesn't support an easy way (either from my perspective, or from an end-user's) to do this. I am thinking about an internal re-write to clean up things anyway though, and part of this may involve adding things like hooks etc. for datasources to provide (e.g. CONFIG_CHANGED and so on) and Tiller could act on them. 

But, I'm a little hesitant right now to add this - it's not that I don't see the benefit, but at that point, Tiller essentially becomes another full init process. The same can be said for #31. Tiller will have to watch over the processes, restart them if they fail, clean up after them, send signals to HUP/restart them on config changes and so on. All this substantially increases the scope of the project, and I need to be 100% sure that:

1. It's worth doing this
2. Tiller is the right place to do this (thinking of the Unix philosophy of "do one thing, and do it well")
3. The code has been thoroughly thought-out

So, this *might* be on the cards for a future release, but it's a little way off yet. As such, I'm going to close this issue but I am aware of this request (and it's something I've thought about myself) so if it's possible to do and I think it'll work, it will get added.

**Comment by EugenMayer** [comment]
as stated, this can be done, already, with consul watch, see gitter :)
