### ISSUE TITLE
[Important doc fix] consul readme uses uri, not url

### ISSUE THREAD

**Issue by EugenMayer** [markround/tiller#23]
This a major, since this is the only mandatory field in the consul configuration. 

here you talk about uri:https://github.com/markround/tiller/blob/master/README-consul.md 
here you talk about url http://www.markround.com/blog/2016/05/12/new-consul-plugin-for-tiller/

in the code, its url https://github.com/markround/tiller/blob/master/lib/tiller/consul.rb#L14

**Comment by markround** [comment]
Doh! Thanks for spotting that!

**Comment by markround** [comment]
Fixed. Thanks again!
