### ISSUE TITLE
Templates are not generated for all environments when using defaults

### ISSUE THREAD

**Issue by EugenMayer** [markround/tiller#29]
If you have an environment which does not need to change anything the defaults defined globally 
(https://github.com/markround/tiller#defaults-plugin)

you would not create a specific environments section for it in the configuration - this should be  pretty common probably either for development or production, depends on what you though of when writing defaults: mytemplate.erb .

When you ommit this environment, you cannot generate the templates for this environment at all. See https://github.com/EugenMayer/tiller-test

run with 

```
docker run --rm eugenmayer/tiller-test -e staging
```

this will produce

```
docker run --rm eugenmayer/tiller-test -e staging                                                                                            130 ↵
Error : Could not load environment staging from common.yaml
tiller v0.7.9 (https://github.com/markround/tiller) <github@markround.com>
Executable: /var/lib/gems/2.1.0/gems/tiller-0.7.9/bin/tiller
Using common.yaml v2 format configuration file
Using configuration from /etc/tiller
Using plugins from /usr/local/lib/tiller
Using environment staging
Template sources loaded [FileTemplateSource]
Data sources loaded [DefaultsDataSource, FileDataSource, EnvironmentDataSource]
#<DefaultsDataSource:0x0000000084ca88> : Using values from v2 format common.yaml
#<DefaultsDataSource:0x0000000084c4c0> : Using values from v2 format common.yaml
```

even using a simple stub like this in environments to at least "introduce them"
```
environments:
  staging:
  development:
    global_values:
       something: 'foor'
```

wont work. So some has to either set a useless dummy value or do something else - sounds unpractical. Either allow this kind of stub and document, that this is needed (simple), or allow picking any env when having such a defaults definition ( sounds more complicated to change though )

**Comment by markround** [comment]
Commit 1b471cf1061b7c7e91aa7d4c34a97447b9b03495 adds support for a stubbed environment like you mentioned, in which case everything comes from the defaults module. See also the test case in that commit.

**Comment by EugenMayer** [comment]
perfect, great!

**Comment by markround** [comment]
Closing as now in 0.7.10. Please open a new issue with any suggestions/improvements for this feature. Thanks again!
