### ISSUE TITLE
[DOC] Compare to Augeas Configuration Parser with Lenses.

### ISSUE THREAD

**Issue by AnneTheAgile** [markround/tiller#3]
hi! I found you from a comment about Tiller [1]. It seems quite helpful, so I'm  posting two question tickets, to ask about Tiller+Augeas #3 and Tiller/Security #4, respectively.  

Tiller's purpose [2] being to provide configurations with pluggable sources seems very  similar in principle to Augeas, which enables writing to standard linux config files like /etc/hosts, INI files, and JSON [3]. At least a couple of people have used it with Docker [4,5]. Both of these people are using the EntryPoint feature, reminiscent of binaries [6].

Have you seen Augeas? How would you compare it to Tiller?
thank you!
AnneTheAgile

Refs;
[1] Environment variables with or without Puppet for Parameterized Docker Containers | James Carr
http://blog.james-carr.org/2013/09/04/parameterized-docker-containers/
````
# Dockerfile using Puppet
CMD cd /docker-registry && ./setup-configs.sh && ./run.sh
# or, without Puppet
docker run -e SETTINGS_FLAVOR=prod -e AWS_ACCESS_KEY_ID=$aws_access_key -e AWS_SECRET_KEY=$aws_secret_key -e S3_BUCKET=$s3_bucket -e WORKER_SECRET_KEY=$worker_key -p 5000:5000 -m 0 samalba/docker-registry
````
Tiller Comment; "You can use [Tiller] to pass environment variables into configuration files, populate them with values from files or other sources."
[2] List of Posts about Tiller, tutorials, release notes. 
http://www.markround.com/blog/categories/tiller/
[2A] Http API for Querying Tiller Configuration From a Running Docker Container - markround.com
http://www.markround.com/blog/2014/10/20/querying-tiller-configuration-from-a-running-docker-container/
[3] Augeas , C language API Library for configuration. "Structured queries and updates to (largely) unstructured configurations" per [6]
http://augeas.net/
[3A]. Augeas example configuring a JSON file. .OpenShift_Quickstarts - Augeas Documentation
http://augeas.net/docs/references/lenses/files/openshift_quickstarts-aug.html
[3B] Detail of [4B], Test_OpenShift_Quickstarts - Augeas Documentation
http://augeas.net/docs/references/lenses/files/tests/test_openshift_quickstarts-aug.html#Test_OpenShift_Quickstarts
[3C] The Augeas JSON Lens. augeas/json.aug at master · hercules-team/augeas
https://github.com/hercules-team/augeas/blob/master/lenses/json.aug
[4] Augeas added to list of ways to configure without recreating a Docker. Marek Goldmann | Customizing the configuration of the WildFly Docker image
https://goldmann.pl/blog/2014/07/23/customizing-the-configuration-of-the-wildfly-docker-image/
[5] Augeas used to configure. Under The Hood of Cloud Computing: Docker: Building and using a base image for Pulp services in Kubernetes
http://cloud-mechanic.blogspot.com/2014/09/docker-building-and-using-base-image.html
[6] Dockerfile Best Practices,  14 July 2013 By Michael Crosby 
````
# Create the /rethinkdb_data dir structure
RUN /usr/bin/rethinkdb create
# Call this command, which takes arguments
ENTRYPOINT ["/usr/bin/rethinkdb"]
# If no arguments are provided, call help.
CMD ["--help"]
````
https://crosbymichael.com/dockerfile-best-practices.html

**Comment by vincent-cn** [comment]
Hi their, this is really an great project that fit our project, and I guess it should also helpful for many others.  
One thing to confirm, when running in Docker container, could tiller script pass through the kill/shutdown signals to child processes so that the real app child process got a change to be gracefully shutdown and avoid the zombie reaping problem? http://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

Thanks,
Vincent

**Comment by markround** [comment]
Vincent, this is a great idea and I'll add this feature for the next release. I've moved it to it's own issue : https://github.com/markround/tiller/issues/7 and will close this one.
