### ISSUE TITLE
New datasource: Vault

### ISSUE THREAD

**Issue by jhmartin** [markround/tiller#34]
Consider allowing Tiller to source secret data from Hashicorp Vault (https://www.vaultproject.io/)

**Comment by liquid-sky** [comment]
@jhmartin @markround I've [raised a PR](https://github.com/markround/tiller/pull/40) with Vault data source. Allows to source secret data as well as templates from Vault.

**Comment by markround** [comment]
@liquid-sky : Merged. This is an awesome feature, and a fantastic PR. Thank you so much again for this addition!

**Comment by liquid-sky** [comment]
Excellent! Thanks @markround.
