### ISSUE TITLE
exec per template

### ISSUE THREAD

**Issue by EugenMayer** [markround/tiller#46]
it would be great to have support to be able to execute an exec-command per template. This is especially useful when you have several services on a e.g. docker container, which tiller is configuring.

Thank you for all the effort!

**Comment by markround** [comment]
See https://github.com/markround/tiller/blob/feature/exec_on_write/features/exec_on_write.feature

This adds the new `exec_on_write` key for templates. You can specify a command in array syntax (e.g. `[ "touch" , "/tmp/test.txt" ]` ) and it well get executed after the template is written. Tiller will then wait for all forked processes to finish before it also exits. Only the main `exec` child process has its exit status recorded.

**Comment by markround** [comment]
Closing as now in 1.0.0. Please re-open if the feature needs some additional work.
