### ISSUE TITLE
production as default environment is scary

### ISSUE THREAD

**Issue by polariss0i** [markround/tiller#5]
I would love to be able to specify in the config what the default environment is instead of it being production.

**Comment by markround** [comment]
Good idea! I'll add a default_environment value or something to
common.yaml.

**Comment by markround** [comment]
OK, 0.3.2 done. I'll build the gem file and push in a little while. In the meantime, I've left the default behaviour as 'production', although you're right - this can be scary, so I'll look at changing it in the next release. In the meantime, you can add `default_environment: dev` in your common.yaml (or whatever). Does this work for you ?

**Comment by polariss0i** [comment]
sounds perfect, that's for the quick turn around!

**Comment by polariss0i** [comment]
I'll close when I verify its working :)

**Comment by markround** [comment]
No problem. I just pushed the gem so you should be able to test without pulling from the git repo now. Let me know how it goes... Any other feedback or ideas are always good to recieve as well :)

**Comment by polariss0i** [comment]
Verified working as expected.
Thanks!
