### ISSUE TITLE
etcd Data Source

### ISSUE THREAD

**Issue by nightwolfzor** [markround/tiller#9]
It would be awesome if we could hook tiller in with etcd configs!

**Comment by markround** [comment]
I've just pushed 0.5.0 which includes some groundwork for this (e.g. the ability to specify different common: parameters per environment which I think we'll need, and also requiring ruby >= 1.9.2).

I've played with etcd a little, but am not overly familiar with it. I plan on reading up on it and working out the best way to integrate Tiller with it, but do you have any suggestions for how you'd like it to work ? If you have some examples that would help a lot.

**Comment by markround** [comment]
I've just pushed release 0.6.0 which includes ZooKeeper plugins. I did this as I'm more familiar with ZooKeeper, but it seems like the approach I took with this plugin could be tweaked to work in pretty much the same way with etcd. Any feedback on this ? The [README-zookeeper.md](https://github.com/markround/tiller/blob/master/README-zookeeper.md) gives an overview on how it works.

**Comment by markround** [comment]
Closing due to lack of feedback. I have implemented a Consul plugin; etcd is still on the cards but is not a high priority for me as I don't currently use it anywhere. If anyone would like to see this given priority, please re-open this issue.
